version: 1.1.1.{build}

environment:
  packageVersion: 1.1.1
  
init:
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: if(!$env:appveyor_repo_tag_name){ $env:nugetVersion = $env:packageVersion+ "-beta-" + $env:appveyor_build_number } else { $env:nugetVersion = $env:appveyor_repo_tag_name}
- ps: Update-AppveyorBuild -Version $env:buildVersion
    
image: Visual Studio 2017
configuration: Release
platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(buildVersion)
  assembly_file_version: $(buildVersion)
  assembly_informational_version: $(nugetVersion)
  
before_build:
- nuget restore

build:
  verbosity: minimal

test:
  assemblies:
    only:
    - Unickq.SpecFlow.Selenium.Example.dll
    
after_build:
- ps: NuGet pack nuget.nuspec -version "$env:nugetVersion"

artifacts:
- path: '**\Unickq.SpecFlow.Selenium*.nupkg'